# pylint: disable=invalid-string-quote
COUNTRY_CODES = {
    "Aruba": "AW",
    "Afghanistan": "AF",
    "Angola": "AO",
    "Anguilla": "AI",
    "Åland Islands": "AX",
    "Albania": "AL",
    "Andorra": "AD",
    "United Arab Emirates": "AE",
    "Argentina": "AR",
    "Armenia": "AM",
    "American Samoa": "AS",
    "Antarctica": "AQ",
    "French Southern Territories": "TF",
    "French Southern and Antarctic Lands": "TF",
    "Antigua and Barbuda": "AG",
    "Australia": "AU",
    "Austria": "AT",
    "Azerbaijan": "AZ",
    "Burundi": "BI",
    "Belgium": "BE",
    "Benin": "BJ",
    "Bonaire, Sint Eustatius and Saba": "BQ",
    "Burkina Faso": "BF",
    "Bangladesh": "BD",
    "Bulgaria": "BG",
    "Bahrain": "BH",
    "Bahamas": "BS",
    "Bosnia and Herzegovina": "BA",
    "Saint Barthélemy": "BL",
    "Belarus": "BY",
    "Belize": "BZ",
    "Bermuda": "BM",
    "Bolivia": "BO",
    "Bolivia, Plurinational State of": "BO",
    "Brazil": "BR",
    "Barbados": "BB",
    "Brunei Darussalam": "BN",
    "Brunei": "BN",
    "Bhutan": "BT",
    "Bouvet Island": "BV",
    "Botswana": "BW",
    "Central African Republic": "CF",
    "Canada": "CA",
    "Cocos (Keeling) Islands": "CC",
    "Switzerland": "CH",
    "Chile": "CL",
    "China": "CN",
    "Côte d'Ivoire": "CI",
    "Ivory Coast": "CI",
    "Cameroon": "CM",
    "Congo, The Democratic Republic of the": "CD",
    "DR Congo": "CD",
    "Congo": "CG",
    "Republic of the Congo": "CG",
    "Cook Islands": "CK",
    "Colombia": "CO",
    "Comoros": "KM",
    "Cabo Verde": "CV",
    "Cape Verde": "CV",
    "Costa Rica": "CR",
    "Cuba": "CU",
    "Curaçao": "CW",
    "Christmas Island": "CX",
    "Cayman Islands": "KY",
    "Cyprus": "CY",
    "Czechia": "CZ",
    "Czech Republic": 'CZ',
    "Germany": "DE",
    "Djibouti": "DJ",
    "Dominica": "DM",
    "Denmark": "DK",
    "Dominican Republic": "DO",
    "Algeria": "DZ",
    "Ecuador": "EC",
    "Egypt": "EG",
    "Eritrea": "ER",
    "Western Sahara": "EH",
    "Spain": "ES",
    "Estonia": "EE",
    "Ethiopia": "ET",
    "Finland": "FI",
    "Fiji": "FJ",
    "Falkland Islands (Malvinas)": "FK",
    "Falkland Islands": "FK",
    "France": "FR",
    "Faroe Islands": "FO",
    "Micronesia, Federated States of": "FM",
    "Micronesia": "FM",
    "Gabon": "GA",
    "United Kingdom": "GB",
    "Georgia": "GE",
    "Guernsey": "GG",
    "Ghana": "GH",
    "Gibraltar": "GI",
    "Guinea": "GN",
    "Guadeloupe": "GP",
    "Gambia": "GM",
    "Guinea-Bissau": "GW",
    "Equatorial Guinea": "GQ",
    "Greece": "GR",
    "Grenada": "GD",
    "Greenland": "GL",
    "Guatemala": "GT",
    "French Guiana": "GF",
    "Guam": "GU",
    "Guyana": "GY",
    "Hong Kong": "HK",
    "Heard Island and McDonald Islands": "HM",
    "Honduras": "HN",
    "Croatia": "HR",
    "Haiti": "HT",
    "Hungary": "HU",
    "Indonesia": "ID",
    "Isle of Man": "IM",
    "India": "IN",
    "British Indian Ocean Territory": "IO",
    "Ireland": "IE",
    "Iran, Islamic Republic of": "IR",
    "Iran": "IR",
    "Iraq": "IQ",
    "Iceland": "IS",
    "Israel": "IL",
    "Italy": "IT",
    "Jamaica": "JM",
    "Jersey": "JE",
    "Jordan": "JO",
    "Japan": "JP",
    "Kazakhstan": "KZ",
    "Kenya": "KE",
    "Kyrgyzstan": "KG",
    "Cambodia": "KH",
    "Kiribati": "KI",
    "Saint Kitts and Nevis": "KN",
    "Korea, Republic of": "KR",
    "South Korea": "KR",
    "Kosovo": "XK",
    "Kuwait": "KW",
    "Lao People's Democratic Republic": "LA",
    "Laos": "LA",
    "Lebanon": "LB",
    "Liberia": "LR",
    "Libya": "LY",
    "Saint Lucia": "LC",
    "Liechtenstein": "LI",
    "Sri Lanka": "LK",
    "Lesotho": "LS",
    "Lithuania": "LT",
    "Luxembourg": "LU",
    "Latvia": "LV",
    "Macao": "MO",
    "Macau": "MO",
    "Saint Martin (French part)": "MF",
    "Saint Martin": "MF",
    "Morocco": "MA",
    "Monaco": "MC",
    "Moldova": "MD",
    "Moldova, Republic of": "MD",
    "Madagascar": "MG",
    "Maldives": "MV",
    "Mexico": "MX",
    "Marshall Islands": "MH",
    "Macedonia, Republic of": "MK",
    "Macedonia": "MK",
    "Mali": "ML",
    "Malta": "MT",
    "Myanmar": "MM",
    "Montenegro": "ME",
    "Mongolia": "MN",
    "Northern Mariana Islands": "MP",
    "Mozambique": "MZ",
    "Mauritania": "MR",
    "Montserrat": "MS",
    "Martinique": "MQ",
    "Mauritius": "MU",
    "Malawi": "MW",
    "Malaysia": "MY",
    "Mayotte": "YT",
    "Namibia": "NA",
    "New Caledonia": "NC",
    "Niger": "NE",
    "Norfolk Island": "NF",
    "Nigeria": "NG",
    "Nicaragua": "NI",
    "Niue": "NU",
    "Netherlands": "NL",
    "Norway": "NO",
    "Nepal": "NP",
    "Nauru": "NR",
    "New Zealand": "NZ",
    "Oman": "OM",
    "Pakistan": "PK",
    "Panama": "PA",
    "Pitcairn": "PN",
    "Pitcairn Islands": "PN",
    "Peru": "PE",
    "Philippines": "PH",
    "Palau": "PW",
    "Papua New Guinea": "PG",
    "Poland": "PL",
    "Puerto Rico": "PR",
    "Korea, Democratic People's Republic of": "KP",
    "North Korea": "KP",
    "Portugal": "PT",
    "Paraguay": "PY",
    "Palestine, State of": "PS",
    "Palestine": "PS",
    "French Polynesia": "PF",
    "Qatar": "QA",
    "Réunion": "RE",
    "Romania": "RO",
    "Russian Federation": "RU",
    "Russia": "RU",
    "Rwanda": "RW",
    "Saudi Arabia": "SA",
    "Sudan": "SD",
    "Senegal": "SN",
    "Singapore": "SG",
    "South Georgia and the South Sandwich Islands": "GS",
    "South Georgia": "GS",
    "Saint Helena, Ascension and Tristan da Cunha": "SH",
    "Svalbard and Jan Mayen": "SJ",
    "Solomon Islands": "SB",
    "Sierra Leone": "SL",
    "El Salvador": "SV",
    "San Marino": "SM",
    "Somalia": "SO",
    "Saint Pierre and Miquelon": "PM",
    "Serbia": "RS",
    "South Sudan": "SS",
    "Sao Tome and Principe": "ST",
    "São Tomé and Príncipe": "ST",
    "Suriname": "SR",
    "Slovakia": "SK",
    "Slovenia": "SI",
    "Sweden": "SE",
    "Swaziland": "SZ",
    "Sint Maarten (Dutch part)": "SX",
    "Sint Maarten": "SX",
    "Seychelles": "SC",
    "Syrian Arab Republic": "SY",
    "Syria": "SY",
    "Turks and Caicos Islands": "TC",
    "Chad": "TD",
    "Togo": "TG",
    "Thailand": "TH",
    "Tajikistan": "TJ",
    "Tokelau": "TK",
    "Turkmenistan": "TM",
    "Timor-Leste": "TL",
    "Tonga": "TO",
    "Trinidad and Tobago": "TT",
    "Tunisia": "TN",
    "Turkey": "TR",
    "Tuvalu": "TV",
    "Taiwan": "TW",
    "Taiwan, Province of China": "TW",
    "Tanzania": "TZ",
    "Tanzania, United Republic of": "TZ",
    "Uganda": "UG",
    "Ukraine": "UA",
    "United States Minor Outlying Islands": "UM",
    "Uruguay": "UY",
    "United States": "US",
    "Uzbekistan": "UZ",
    "Holy See (Vatican City State)": "VA",
    "Vatican City": "VA",
    "Saint Vincent and the Grenadines": "VC",
    "Venezuela": "VE",
    "Venezuela, Bolivarian Republic of": "VE",
    "Virgin Islands, British": "VG",
    "British Virgin Islands": "VG",
    "Virgin Islands, U.S.": "VI",
    "United States Virgin Islands": "VI",
    "Vietnam": "VN",
    "Viet Nam": "VN",
    "Vanuatu": "VU",
    "Wallis and Futuna": "WF",
    "Samoa": "WS",
    "Yemen": "YE",
    "South Africa": "ZA",
    "Zambia": "ZM",
    "Zimbabwe": "ZW"}

COUNTRIES = {
    'AW': ['Aruba'],
    'AF': ['Afghanistan'],
    'AO': ['Angola'],
    'AI': ['Anguilla'],
    'AX': ['Åland Islands'],
    'AL': ['Albania'],
    'AD': ['Andorra'],
    'AE': ['United Arab Emirates'],
    'AR': ['Argentina'],
    'AM': ['Armenia'],
    'AS': ['American Samoa'],
    'AQ': ['Antarctica'],
    'TF': ['French Southern Territories', 'French Southern and Antarctic Lands'],
    'AG': ['Antigua and Barbuda'],
    'AU': ['Australia'],
    'AT': ['Austria'],
    'AZ': ['Azerbaijan'],
    'BI': ['Burundi'],
    'BE': ['Belgium'],
    'BJ': ['Benin'],
    'BQ': ['Bonaire, Sint Eustatius and Saba'],
    'BF': ['Burkina Faso'],
    'BD': ['Bangladesh'],
    'BG': ['Bulgaria'],
    'BH': ['Bahrain'],
    'BS': ['Bahamas'],
    'BA': ['Bosnia and Herzegovina'],
    'BL': ['Saint Barthélemy'],
    'BY': ['Belarus'],
    'BZ': ['Belize'],
    'BM': ['Bermuda'],
    'BO': ['Bolivia', 'Bolivia, Plurinational State of'],
    'BR': ['Brazil'],
    'BB': ['Barbados'],
    'BN': ['Brunei Darussalam', 'Brunei'],
    'BT': ['Bhutan'],
    'BV': ['Bouvet Island'],
    'BW': ['Botswana'],
    'CF': ['Central African Republic'],
    'CA': ['Canada'],
    'CC': ['Cocos (Keeling) Islands'],
    'CH': ['Switzerland'],
    'CL': ['Chile'],
    'CN': ['China'],
    'CI': ["Côte d'Ivoire", 'Ivory Coast'],
    'CM': ['Cameroon'],
    'CD': ['Congo, The Democratic Republic of the', 'DR Congo'],
    'CG': ['Congo', 'Republic of the Congo'],
    'CK': ['Cook Islands'],
    'CO': ['Colombia'],
    'KM': ['Comoros'],
    'CV': ['Cabo Verde', 'Cape Verde'],
    'CR': ['Costa Rica'],
    'CU': ['Cuba'],
    'CW': ['Curaçao'],
    'CX': ['Christmas Island'],
    'KY': ['Cayman Islands'],
    'CY': ['Cyprus'],
    'CZ': ['Czechia', 'Czech Republic'],
    'DE': ['Germany'],
    'DJ': ['Djibouti'],
    'DM': ['Dominica'],
    'DK': ['Denmark'],
    'DO': ['Dominican Republic'],
    'DZ': ['Algeria'],
    'EC': ['Ecuador'],
    'EG': ['Egypt'],
    'ER': ['Eritrea'],
    'EH': ['Western Sahara'],
    'ES': ['Spain'],
    'EE': ['Estonia'],
    'ET': ['Ethiopia'],
    'FI': ['Finland'],
    'FJ': ['Fiji'],
    'FK': ['Falkland Islands (Malvinas)', 'Falkland Islands'],
    'FR': ['France'],
    'FO': ['Faroe Islands'],
    'FM': ['Micronesia, Federated States of', 'Micronesia'],
    'GA': ['Gabon'],
    'GB': ['United Kingdom'],
    'GE': ['Georgia'],
    'GG': ['Guernsey'],
    'GH': ['Ghana'],
    'GI': ['Gibraltar'],
    'GN': ['Guinea'],
    'GP': ['Guadeloupe'],
    'GM': ['Gambia'],
    'GW': ['Guinea-Bissau'],
    'GQ': ['Equatorial Guinea'],
    'GR': ['Greece'],
    'GD': ['Grenada'],
    'GL': ['Greenland'],
    'GT': ['Guatemala'],
    'GF': ['French Guiana'],
    'GU': ['Guam'],
    'GY': ['Guyana'],
    'HK': ['Hong Kong'],
    'HM': ['Heard Island and McDonald Islands'],
    'HN': ['Honduras'],
    'HR': ['Croatia'],
    'HT': ['Haiti'],
    'HU': ['Hungary'],
    'ID': ['Indonesia'],
    'IM': ['Isle of Man'],
    'IN': ['India'],
    'IO': ['British Indian Ocean Territory'],
    'IE': ['Ireland'],
    'IR': ['Iran, Islamic Republic of', 'Iran'],
    'IQ': ['Iraq'],
    'IS': ['Iceland'],
    'IL': ['Israel'],
    'IT': ['Italy'],
    'JM': ['Jamaica'],
    'JE': ['Jersey'],
    'JO': ['Jordan'],
    'JP': ['Japan'],
    'KZ': ['Kazakhstan'],
    'KE': ['Kenya'],
    'KG': ['Kyrgyzstan'],
    'KH': ['Cambodia'],
    'KI': ['Kiribati'],
    'KN': ['Saint Kitts and Nevis'],
    'KR': ['Korea, Republic of', 'South Korea'],
    'XK': ['Kosovo'],
    'KW': ['Kuwait'],
    'LA': ["Lao People's Democratic Republic", 'Laos'],
    'LB': ['Lebanon'],
    'LR': ['Liberia'],
    'LY': ['Libya'],
    'LC': ['Saint Lucia'],
    'LI': ['Liechtenstein'],
    'LK': ['Sri Lanka'],
    'LS': ['Lesotho'],
    'LT': ['Lithuania'],
    'LU': ['Luxembourg'],
    'LV': ['Latvia'],
    'MO': ['Macao', 'Macau'],
    'MF': ['Saint Martin (French part)', 'Saint Martin'],
    'MA': ['Morocco'],
    'MC': ['Monaco'],
    'MD': ['Moldova', 'Moldova, Republic of'],
    'MG': ['Madagascar'],
    'MV': ['Maldives'],
    'MX': ['Mexico'],
    'MH': ['Marshall Islands'],
    'MK': ['Macedonia, Republic of', 'Macedonia'],
    'ML': ['Mali'],
    'MT': ['Malta'],
    'MM': ['Myanmar'],
    'ME': ['Montenegro'],
    'MN': ['Mongolia'],
    'MP': ['Northern Mariana Islands'],
    'MZ': ['Mozambique'],
    'MR': ['Mauritania'],
    'MS': ['Montserrat'],
    'MQ': ['Martinique'],
    'MU': ['Mauritius'],
    'MW': ['Malawi'],
    'MY': ['Malaysia'],
    'YT': ['Mayotte'],
    'NA': ['Namibia'],
    'NC': ['New Caledonia'],
    'NE': ['Niger'],
    'NF': ['Norfolk Island'],
    'NG': ['Nigeria'],
    'NI': ['Nicaragua'],
    'NU': ['Niue'],
    'NL': ['Netherlands'],
    'NO': ['Norway'],
    'NP': ['Nepal'],
    'NR': ['Nauru'],
    'NZ': ['New Zealand'],
    'OM': ['Oman'],
    'PK': ['Pakistan'],
    'PA': ['Panama'],
    'PN': ['Pitcairn', 'Pitcairn Islands'],
    'PE': ['Peru'],
    'PH': ['Philippines'],
    'PW': ['Palau'],
    'PG': ['Papua New Guinea'],
    'PL': ['Poland'],
    'PR': ['Puerto Rico'],
    'KP': ["Korea, Democratic People's Republic of", 'North Korea'],
    'PT': ['Portugal'],
    'PY': ['Paraguay'],
    'PS': ['Palestine, State of', 'Palestine'],
    'PF': ['French Polynesia'],
    'QA': ['Qatar'],
    'RE': ['Réunion'],
    'RO': ['Romania'],
    'RU': ['Russian Federation', 'Russia'],
    'RW': ['Rwanda'],
    'SA': ['Saudi Arabia'],
    'SD': ['Sudan'],
    'SN': ['Senegal'],
    'SG': ['Singapore'],
    'GS': ['South Georgia and the South Sandwich Islands', 'South Georgia'],
    'SH': ['Saint Helena, Ascension and Tristan da Cunha'],
    'SJ': ['Svalbard and Jan Mayen'],
    'SB': ['Solomon Islands'],
    'SL': ['Sierra Leone'],
    'SV': ['El Salvador'],
    'SM': ['San Marino'],
    'SO': ['Somalia'],
    'PM': ['Saint Pierre and Miquelon'],
    'RS': ['Serbia'],
    'SS': ['South Sudan'],
    'ST': ['Sao Tome and Principe', 'São Tomé and Príncipe'],
    'SR': ['Suriname'],
    'SK': ['Slovakia'],
    'SI': ['Slovenia'],
    'SE': ['Sweden'],
    'SZ': ['Swaziland'],
    'SX': ['Sint Maarten (Dutch part)', 'Sint Maarten'],
    'SC': ['Seychelles'],
    'SY': ['Syrian Arab Republic', 'Syria'],
    'TC': ['Turks and Caicos Islands'],
    'TD': ['Chad'],
    'TG': ['Togo'],
    'TH': ['Thailand'],
    'TJ': ['Tajikistan'],
    'TK': ['Tokelau'],
    'TM': ['Turkmenistan'],
    'TL': ['Timor-Leste'],
    'TO': ['Tonga'],
    'TT': ['Trinidad and Tobago'],
    'TN': ['Tunisia'],
    'TR': ['Turkey'],
    'TV': ['Tuvalu'],
    'TW': ['Taiwan', 'Taiwan, Province of China'],
    'TZ': ['Tanzania', 'Tanzania, United Republic of'],
    'UG': ['Uganda'],
    'UA': ['Ukraine'],
    'UM': ['United States Minor Outlying Islands'],
    'UY': ['Uruguay'],
    'US': ['United States'],
    'UZ': ['Uzbekistan'],
    'VA': ['Holy See (Vatican City State)', 'Vatican City'],
    'VC': ['Saint Vincent and the Grenadines'],
    'VE': ['Venezuela', 'Venezuela, Bolivarian Republic of'],
    'VG': ['Virgin Islands, British', 'British Virgin Islands'],
    'VI': ['Virgin Islands, U.S.', 'United States Virgin Islands'],
    'VN': ['Vietnam', 'Viet Nam'],
    'VU': ['Vanuatu'],
    'WF': ['Wallis and Futuna'],
    'WS': ['Samoa'],
    'YE': ['Yemen'],
    'ZA': ['South Africa'],
    'ZM': ['Zambia'],
    'ZW': ['Zimbabwe']
}
